import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { SiteFooter } from '../../components/SiteFooter';
import { SiteHeader } from '../../components/SiteHeader';
import { useLocale } from '../../context/LocaleContext';
import { getPublicPage } from '../../lib/cms-api';
import { Seo } from '../../components/Seo';

type Section={id:string;section_key:string;title_en:string;title_ar:string;body_en:string;body_ar:string;settings?:Record<string,any>};
const pick=(language:'en'|'ar',en?:string,ar?:string)=>language==='ar'?(ar||en||''):(en||ar||'');

export default function AboutPage(){const {language}=useLocale();const [sections,setSections]=useState<Section[]|null>(null);const [pageMeta,setPageMeta]=useState<any>(null);useEffect(()=>{void getPublicPage('about-us').then(record=>{setSections(record?.sections||[]);setPageMeta(record?.page||null)})},[]);const byKey=useMemo(()=>Object.fromEntries((sections||[]).map(section=>[section.section_key,section])),[sections]);const item=(key:string)=>byKey[key] as Section|undefined;const text=(section?:Section,field:'title'|'body'='title')=>pick(language,section?.[`${field}_en` as keyof Section] as string,section?.[`${field}_ar` as keyof Section] as string);const list=(section?:Section)=>Array.isArray(section?.settings?.items)?section!.settings.items:[];const hero=item('hero'),role=item('role'),approach=item('approach'),archive=item('archive');if(!sections)return <main id="main-content"><SiteHeader/><section className="page-loading"/></main>;return <main id="main-content"><Seo title={pick(language,pageMeta?.seo_title_en,pageMeta?.seo_title_ar)||text(hero)} description={pick(language,pageMeta?.seo_description_en,pageMeta?.seo_description_ar)||text(hero,'body')}/><SiteHeader/><section className="page-hero about-hero"><p className="eyebrow">{pick(language,hero?.settings?.eyebrow_en,hero?.settings?.eyebrow_ar)}</p><h1>{text(hero)}</h1><p>{text(hero,'body')}</p></section><section className="about-role"><p className="section-no">01 <small>{pick(language,role?.settings?.label_en,role?.settings?.label_ar)}</small></p><div><h2>{text(role)}</h2><p className="lead">{text(role,'body')}</p></div></section><section className="about-approach"><p className="section-no">02 <small>{pick(language,approach?.settings?.label_en,approach?.settings?.label_ar)}</small></p><h2>{text(approach)}</h2><p>{text(approach,'body')}</p><div className="about-pillars">{list(approach).map((x:any,index:number)=><article key={x.title_en||index}><span>0{index+1}</span><h3>{pick(language,x.title_en,x.title_ar)}</h3><p>{pick(language,x.body_en,x.body_ar)}</p></article>)}</div></section><section className="about-archive"><p className="section-no">03 <small>{pick(language,archive?.settings?.label_en,archive?.settings?.label_ar)}</small></p><div><h2>{text(archive)}</h2><p className="lead">{text(archive,'body')}</p></div><div className="archive-records">{list(archive).map((x:any,index:number)=><article key={x.title_en||index}><span>0{index+1}</span><small>{pick(language,x.meta_en,x.meta_ar)}</small><strong>{pick(language,x.title_en,x.title_ar)}</strong></article>)}</div></section><section className="about-close"><p>{language==='ar'?'القيادة والحوكمة':'Leadership and governance'}</p><Link to="/board">{language==='ar'?'تعرف إلى مجلس الإدارة ↗':'Meet the Board ↗'}</Link></section><SiteFooter/></main>}
