import { useEffect, useMemo, useState } from 'react';
import { SiteFooter } from '../../components/SiteFooter';
import { SiteHeader } from '../../components/SiteHeader';
import { LeadershipCard } from '../../components/LeadershipCard';
import { useCms } from '../../context/CmsContext';
import { useLocale } from '../../context/LocaleContext';
import { getPublicPage } from '../../lib/cms-api';
import type { LeadershipRecord } from '../../types/cms';
import { Seo } from '../../components/Seo';

type Section={title_en:string;title_ar:string;body_en:string;body_ar:string;settings?:Record<string,any>};
const pick=(language:'en'|'ar',en?:string,ar?:string)=>language==='ar'?(ar||en||''):(en||ar||'');
export default function BoardPage(){const {language}=useLocale();const {publicLeaders}=useCms();const [intro,setIntro]=useState<Section|null>(null);const [pageMeta,setPageMeta]=useState<any>(null);useEffect(()=>{void getPublicPage('board').then(record=>{setIntro(record?.sections?.find((section:any)=>section.section_key==='intro')||null);setPageMeta(record?.page||null)})},[]);const leaders=useMemo(()=>[...publicLeaders].sort((a,b)=>a.order-b.order),[publicLeaders]);const chairman=leaders.find(x=>x.leadershipRole==='chairman');const ceo=leaders.find(x=>x.leadershipRole==='ceo');const members=leaders.filter(x=>x.leadershipRole==='board_member');const section=(label:string,records:LeadershipRecord[])=>records.length?<section className="board-group"><p className="eyebrow">{label}</p><div className={records.length===1?'board-featured':'board-grid'}>{records.map(record=><LeadershipCard leader={record} key={record.id}/>)}</div></section>:null;const title=pick(language,pageMeta?.seo_title_en,pageMeta?.seo_title_ar)||pick(language,intro?.title_en,intro?.title_ar)||'AIIF Board';const description=pick(language,pageMeta?.seo_description_en,pageMeta?.seo_description_ar)||pick(language,intro?.body_en,intro?.body_ar)||title;return <main id="main-content"><Seo title={title} description={description} type="profile"/><SiteHeader/><section className="page-hero board-hero"><p className="eyebrow">{pick(language,intro?.settings?.eyebrow_en,intro?.settings?.eyebrow_ar)}</p><h1>{pick(language,intro?.title_en,intro?.title_ar)}</h1><p>{pick(language,intro?.body_en,intro?.body_ar)}</p></section><section className="board-content">{section(language==='ar'?'رئيس مجلس الإدارة':'Chairman',chairman?[chairman]:[])}{section(language==='ar'?'الرئيس التنفيذي':'Chief Executive Officer',ceo?[ceo]:[])}{section(language==='ar'?'أعضاء مجلس الإدارة':'Board Members',members)}{!leaders.length&&<div className="board-empty"><p>{language==='ar'?'ستظهر سجلات مجلس الإدارة هنا بعد اعتمادها في نظام إدارة المحتوى.':'Approved Board records will appear here from the CMS.'}</p></div>}</section><SiteFooter/></main>}
