import { ChangeEvent, DragEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { CmsSidebar } from '../../components/CmsSidebar';
import { SiteHeader } from '../../components/SiteHeader';
import { StatusPill } from '../../components/StatusPill';
import { formatBytes, uploadAiifImage } from '../../lib/media-upload';
import { supabase } from '../../lib/supabase';

type LeaderForm={id?:string;full_name_en:string;full_name_ar:string;honorific:string;position_en:string;position_ar:string;country:string;leadership_role:string;display_order:number;status:string;homepage_visible:boolean;active:boolean;photo_path:string;photo_alt_en:string;photo_alt_ar:string;short_bio_en:string;short_bio_ar:string;full_bio_en:string;full_bio_ar:string;linkedin_url:string;verification_note:string};
const empty:LeaderForm={full_name_en:'',full_name_ar:'',honorific:'',position_en:'',position_ar:'',country:'',leadership_role:'board_member',display_order:10,status:'draft',homepage_visible:false,active:true,photo_path:'',photo_alt_en:'',photo_alt_ar:'',short_bio_en:'',short_bio_ar:'',full_bio_en:'',full_bio_ar:'',linkedin_url:'',verification_note:''};
const roles=[['chairman','Chairman'],['ceo','CEO'],['board_member','Board member'],['historical','Historical leadership']];

export default function CmsLeadershipPage(){const [records,setRecords]=useState<any[]>([]);const [form,setForm]=useState<LeaderForm>(empty);const [message,setMessage]=useState('');const [details,setDetails]=useState('');const [uploading,setUploading]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const field=(key:keyof LeaderForm)=>(event:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(current=>({...current,[key]:event.target instanceof HTMLInputElement&&event.target.type==='checkbox'?event.target.checked:event.target.type==='number'?Number(event.target.value):event.target.value}));const load=async()=>{const {data,error}=await supabase.from('leadership_records').select('*').order('leadership_role').order('display_order');if(error)setMessage(error.message);else setRecords(data||[])};useEffect(()=>{void load()},[]);
  const edit=(record:any)=>{setForm({...empty,...record,photo_path:record.photo_path||'',photo_alt_en:record.photo_alt_en||'',photo_alt_ar:record.photo_alt_ar||'',linkedin_url:record.linkedin_url||''});setDetails('');window.scrollTo({top:0,behavior:'smooth'});};
  const useFile=async(file?:File)=>{if(!file)return;setUploading(true);setMessage('Uploading portrait…');try{const upload=await uploadAiifImage(file,'leadership');setForm(current=>({...current,photo_path:upload.publicUrl,photo_alt_en:current.photo_alt_en||current.full_name_en||file.name.replace(/\.[^.]+$/,''),photo_alt_ar:current.photo_alt_ar||current.full_name_ar||file.name.replace(/\.[^.]+$/,'')}));setDetails(`${upload.details.width} × ${upload.details.height} px · ${formatBytes(upload.details.size)}`);setMessage('Portrait uploaded.')}catch(error){setMessage(error instanceof Error?error.message:'Portrait upload failed.')}finally{setUploading(false)}};const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();void useFile(event.dataTransfer.files[0])};
  const save=async(event:FormEvent)=>{event.preventDefault();setMessage('Saving…');const {id,...values}=form;const payload={...values,photo_path:values.photo_path||null,linkedin_url:values.linkedin_url||null};const result=id?await supabase.from('leadership_records').update(payload).eq('id',id):await supabase.from('leadership_records').insert(payload);if(result.error){setMessage(result.error.message);return}setMessage('Leadership record saved.');setForm(empty);setDetails('');void load()};
  return <div className="admin"><CmsSidebar/><main className="admin-main"><SiteHeader admin/><p className="eyebrow">CMS / Board & leadership</p><h1>Board & leadership</h1><p className="lead">Every record can be added, edited, moved, hidden or published here — including the current CEO. There is no permanent person in this screen.</p><section className="cms-section"><div className="cms-toolbar"><h2>{form.id?'Edit leadership record':'Add leadership record'}</h2>{form.id&&<button className="plain-button" type="button" onClick={()=>setForm(empty)}>Start a new record</button>}</div><form className="content-form" onSubmit={save}><label>Full name — English<input required value={form.full_name_en} onChange={field('full_name_en')}/></label><label lang="ar" dir="rtl">الاسم الكامل — العربية<input required value={form.full_name_ar} onChange={field('full_name_ar')}/></label><label>Title / honorific<input value={form.honorific} onChange={field('honorific')} placeholder="H.E. (optional)"/></label><label>Role on the board<select value={form.leadership_role} onChange={field('leadership_role')}>{roles.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><small>CEO is displayed before board members. Use the order field to arrange people within a group.</small></label><label>Position — English<input required value={form.position_en} onChange={field('position_en')}/></label><label lang="ar" dir="rtl">المنصب — العربية<input required value={form.position_ar} onChange={field('position_ar')}/></label><label>Country<input value={form.country} onChange={field('country')}/></label><label>Display order<input type="number" value={form.display_order} onChange={field('display_order')}/></label><label>Publishing status<select value={form.status} onChange={field('status')}><option value="draft">Draft — private</option><option value="needs_verification">Needs verification — private</option><option value="approved">Approved — public</option><option value="published">Published — public</option><option value="archived">Archived — hidden</option></select></label><label className="toggle-row"><input type="checkbox" checked={form.homepage_visible} onChange={field('homepage_visible')}/>Show on Home page</label><label className="toggle-row"><input type="checkbox" checked={form.active} onChange={field('active')}/>Active current leadership record</label>
    <div className="form-wide"><p className="field-label">Portrait</p><div className="image-dropzone" onDragOver={event=>event.preventDefault()} onDrop={drop} onClick={()=>inputRef.current?.click()} role="button" tabIndex={0}><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void useFile(event.target.files?.[0])}/><b>{uploading?'Uploading…':'Drop a portrait here or choose a file'}</b><span>JPG, PNG or WebP · maximum 8 MB</span>{details&&<small>{details}</small>}</div>{form.photo_path&&<div className="image-preview"><img src={form.photo_path} alt="Selected portrait"/><button className="plain-button" type="button" onClick={()=>setForm(current=>({...current,photo_path:''}))}>Remove portrait</button></div>}</div><label>Portrait description — English<input value={form.photo_alt_en} onChange={field('photo_alt_en')}/></label><label lang="ar" dir="rtl">وصف الصورة — العربية<input value={form.photo_alt_ar} onChange={field('photo_alt_ar')}/></label>
    <label className="form-wide">Short biography — English<textarea value={form.short_bio_en} onChange={field('short_bio_en')}/></label><label className="form-wide" lang="ar" dir="rtl">نبذة مختصرة — العربية<textarea value={form.short_bio_ar} onChange={field('short_bio_ar')}/></label><label className="form-wide">Full biography — English<textarea value={form.full_bio_en} onChange={field('full_bio_en')}/></label><label className="form-wide" lang="ar" dir="rtl">السيرة الكاملة — العربية<textarea value={form.full_bio_ar} onChange={field('full_bio_ar')}/></label><label>LinkedIn or official profile (optional)<input type="url" value={form.linkedin_url} onChange={field('linkedin_url')}/></label><label>Internal note (not public)<textarea value={form.verification_note} onChange={field('verification_note')}/></label><button className="button" disabled={uploading} type="submit">{form.id?'Save changes':'Create record'}</button></form>{message&&<p className="form-message">{message}</p>}</section><section className="cms-section"><h2>Leadership records</h2>{records.map(record=><article className="cms-row" key={record.id}><div><p className="eyebrow">{roles.find(([value])=>value===record.leadership_role)?.[1]||'Board member'} · position {record.display_order}</p><h3>{record.full_name_en}</h3><p>{record.position_en} · {record.country||'No country set'}</p></div><div><StatusPill>{record.status}</StatusPill><button className="plain-button" onClick={()=>edit(record)}>Edit record</button></div></article>)}{!records.length&&<p>No leadership records yet.</p>}</section></main></div>}
