import { ChangeEvent, DragEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { CmsSidebar } from '../../components/CmsSidebar';
import { SiteHeader } from '../../components/SiteHeader';
import { formatBytes, uploadAiifImage } from '../../lib/media-upload';
import { supabase } from '../../lib/supabase';

type MediaForm={id?:string;media_type:string;slug:string;title_en:string;title_ar:string;excerpt_en:string;excerpt_ar:string;article_en:string;article_ar:string;image_path:string;image_alt_en:string;image_alt_ar:string;image_caption_en:string;image_caption_ar:string;external_url:string;published_on:string;featured:boolean;status:string};
const empty:MediaForm={media_type:'news',slug:'',title_en:'',title_ar:'',excerpt_en:'',excerpt_ar:'',article_en:'',article_ar:'',image_path:'',image_alt_en:'',image_alt_ar:'',image_caption_en:'',image_caption_ar:'',external_url:'',published_on:'',featured:false,status:'draft'};
const statusHelp:Record<string,string>={draft:'Private — not visible on the website.',approved:'Approved internally — still private.',published:'Visible on the public website.',archived:'Kept in the CMS but hidden from the website.'};

export default function CmsMediaPage(){
  const [items,setItems]=useState<any[]>([]); const [form,setForm]=useState<MediaForm>(empty); const [message,setMessage]=useState(''); const [uploading,setUploading]=useState(false); const [imageDetails,setImageDetails]=useState(''); const inputRef=useRef<HTMLInputElement>(null);
  const field=(key:keyof MediaForm)=>(event:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(current=>({...current,[key]:event.target instanceof HTMLInputElement&&event.target.type==='checkbox'?event.target.checked:event.target.value}));
  const load=async()=>{const {data,error}=await supabase.from('media_items').select('*').order('updated_at',{ascending:false});if(error)setMessage(error.message);else setItems(data||[])}; useEffect(()=>{void load()},[]);
  const edit=(item:any)=>{setForm({...empty,...item,image_path:item.image_path||'',image_alt_en:item.image_alt_en||'',image_alt_ar:item.image_alt_ar||'',image_caption_en:item.image_caption_en||'',image_caption_ar:item.image_caption_ar||'',external_url:item.external_url||'',published_on:item.published_on||''});setImageDetails('');window.scrollTo({top:0,behavior:'smooth'});};
  const useFile=async(file?:File)=>{if(!file)return;setUploading(true);setMessage('Uploading image…');try{const upload=await uploadAiifImage(file,'media');setForm(current=>({...current,image_path:upload.publicUrl,image_alt_en:current.image_alt_en||file.name.replace(/\.[^.]+$/,''),image_alt_ar:current.image_alt_ar||file.name.replace(/\.[^.]+$/,'')}));setImageDetails(`${upload.details.width} × ${upload.details.height} px · ${formatBytes(upload.details.size)} · ${upload.details.type.replace('image/','').toUpperCase()}`);setMessage('Image uploaded. Add a useful description in both languages.')}catch(error){setMessage(error instanceof Error?error.message:'Image upload failed.')}finally{setUploading(false)}};
  const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();void useFile(event.dataTransfer.files[0])};
  const save=async(event:FormEvent)=>{event.preventDefault();setMessage('Saving…');const {id,...values}=form;const payload={...values,image_path:values.image_path||null,external_url:values.external_url||null,published_on:values.published_on||null};const result=id?await supabase.from('media_items').update(payload).eq('id',id):await supabase.from('media_items').insert(payload);if(result.error){setMessage(result.error.message);return}setMessage('Saved.');setForm(empty);setImageDetails('');void load()};
  return <div className="admin"><CmsSidebar/><main className="admin-main"><SiteHeader admin/><p className="eyebrow">CMS / Media Center</p><h1>Media Center</h1><p className="lead">Add news, press releases, awards and publications. Publish only when the English, Arabic and image details are complete.</p><section className="cms-section"><div className="cms-toolbar"><h2>{form.id?'Edit item':'Add item'}</h2>{form.id&&<button className="plain-button" type="button" onClick={()=>{setForm(empty);setImageDetails('')}}>Start a new item</button>}</div><form className="content-form" onSubmit={save}>
    <label>Content type<select value={form.media_type} onChange={field('media_type')}><option value="news">News</option><option value="press_release">Press release</option><option value="award">Award</option><option value="publication">Publication</option></select></label>
    <label>Publishing status<select value={form.status} onChange={field('status')}><option value="draft">Draft — private</option><option value="approved">Approved — private</option><option value="published">Published — public</option><option value="archived">Archived — hidden</option></select><small>{statusHelp[form.status]}</small></label>
    <label>Website address (slug)<input required value={form.slug} onChange={field('slug')} placeholder="example-news-title"/><small>Use lowercase words separated with hyphens.</small></label><label>Publication date<input type="date" value={form.published_on} onChange={field('published_on')}/></label>
    <label>Title — English<input required value={form.title_en} onChange={field('title_en')}/></label><label lang="ar" dir="rtl">العنوان — العربية<input required value={form.title_ar} onChange={field('title_ar')}/></label>
    <label className="form-wide">Short summary — English<textarea value={form.excerpt_en} onChange={field('excerpt_en')}/></label><label className="form-wide" lang="ar" dir="rtl">الملخص — العربية<textarea value={form.excerpt_ar} onChange={field('excerpt_ar')}/></label>
    <label className="form-wide">Full article — English<textarea value={form.article_en} onChange={field('article_en')}/></label><label className="form-wide" lang="ar" dir="rtl">المادة الكاملة — العربية<textarea value={form.article_ar} onChange={field('article_ar')}/></label>
    <div className="form-wide"><p className="field-label">Cover image</p><div className="image-dropzone" onDragOver={event=>event.preventDefault()} onDrop={drop} onClick={()=>inputRef.current?.click()} role="button" tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')inputRef.current?.click()}}><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void useFile(event.target.files?.[0])}/><b>{uploading?'Uploading…':'Drop an image here or choose a file'}</b><span>JPG, PNG or WebP · maximum 8 MB</span>{imageDetails&&<small>{imageDetails}</small>}</div>{form.image_path&&<div className="image-preview"><img src={form.image_path} alt="Selected cover"/><button type="button" className="plain-button" onClick={()=>setForm(current=>({...current,image_path:''}))}>Remove image</button></div>}</div>
    <label>Image description — English<input value={form.image_alt_en} onChange={field('image_alt_en')} placeholder="Describe what appears in the image"/></label><label lang="ar" dir="rtl">وصف الصورة — العربية<input value={form.image_alt_ar} onChange={field('image_alt_ar')} placeholder="صف ما يظهر في الصورة"/></label>
    <label>Image caption — English<input value={form.image_caption_en} onChange={field('image_caption_en')}/></label><label lang="ar" dir="rtl">تعليق الصورة — العربية<input value={form.image_caption_ar} onChange={field('image_caption_ar')}/></label>
    <label className="form-wide">Original official source link<input type="url" value={form.external_url} onChange={field('external_url')} placeholder="https://…"/><small>Add the original AIIF page, approved partner announcement or PDF. The public article stays on this website and shows this link as its source.</small></label><label className="toggle-row"><input type="checkbox" checked={form.featured} onChange={field('featured')}/>Show as a featured item</label><button className="button" disabled={uploading} type="submit">{form.id?'Save changes':'Create item'}</button></form>{message&&<p className="form-message">{message}</p>}</section><section className="cms-section"><h2>Saved items</h2>{items.map(item=><article className="cms-row" key={item.id}><div><p className="eyebrow">{item.media_type.replace('_',' ')} · {item.status}</p><h3>{item.title_en}</h3><p>{item.published_on||'No publication date'} · {item.slug}</p></div><button className="plain-button" onClick={()=>edit(item)}>Edit item</button></article>)}{!items.length&&<p>No media records yet.</p>}</section></main></div>;
}
